### ISSUE TITLE
What is to be tweaked in the config.js file?

### ISSUE THREAD

**Issue by DreamFace** [af83/auth_server#3]
The README says to tweak the config.js file in auth_server. What exactly are we expected to modify and in what way? Running src/server.js with the config.js as is, crashes with a CursorId null in the MongoDB driver, pointing maybe to an incorrect data initialisation in  mongo? What did we forget again?

DreamFace Interactive

**Comment by francois2metz** [comment]
Duplicate of #2.

The mongodb driver seems broken. I'm on it.

**Comment by francois2metz** [comment]
Can you retry please? The issue #2 is resolved.
